### ISSUE TITLE
Scrutinizer Config

### ISSUE THREAD

**Issue by GrahamCampbell** [thephpleague/factory-muffin#241]
@scottrobertson Our scrutinizer config needs a small change.

Can you find:

``` yaml
    external_code_coverage:
        timeout: '3600'
        runs: 3
```

and change the number of runs to `5` please.
