### ISSUE TITLE
Cannot define model

### ISSUE THREAD

**Issue by StefanGramadnikov** [thephpleague/factory-muffin#427]
Hi,

I'm using codeception and symfony 2.8 with doctrine 2. I'm writing unit tests with codeception and I want to pre load some data with Factory Muffin, but I'm getting stuck. Here is my setup:

- Enabled Modules 

```
modules:
    enabled:
        - Asserts
        - Symfony
        - Db
        - Doctrine2:
            depends: Symfony
        - \Helper\Unit
        - DataFactory:
            factories: tests/_support/factories
            depends: Doctrine2
```

note: I have installed factory muffin and the faker through composer

- I have the factories folder in tests/_support/factories

- My factories are in the folder above

- My factory looks like this

```
<?php
use League\FactoryMuffin\Faker\Facade as Faker;

$fm->define('AppBundle\Entity\User', [
    'name' => Faker::name(),
    'email' => Faker::email(),
    'isActive' => Faker::boolean(100),
    'isDeleted' => Faker::boolean(0),
    'type' => 'user',
    'apiKey' => 'test'
]);
```

My problem is that when I run the tests I get ->
```

[League\FactoryMuffin\Exceptions\DefinitionAlreadyDefinedException]     
The model definition 'AppBundle\Entity\User' has already been defined
```

I was trying to debug it and saw that the method define in FactoryMuffin.php is being called two times and I couldn't figure out why. The second time is where it throws the exception.

If I try $fm->make instead of define I get
```
[League\FactoryMuffin\Exceptions\DefinitionNotFoundException]  
 The model definition 'AppBundle\Entity\User' is undefined. 
```

Can you please tell me if I'm doing something wrong or check if there is some mistake in the code. 
If you need more info about my configuration I'll be in touch.

Thank you
